name: Unit tests PHP
on:
  workflow_dispatch:
  push:
jobs:
  tests-unit-php:
    uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
    with:
      PHPUNIT_ARGS: '--testsuite=Unit --coverage-text'
      PHP_MATRIX: >-
        ["8.0", "8.1"]
